version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: always
    command: sh -c 'cd src && gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application'
    expose:
      - 8000
    env_file: ./.env.prod
    depends_on:
      - mongodb
  nginx:
    image: nginx
    ports:
      - "1337:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../sync-party-site/app/build:/var/www/client # https://github.com/yakimenko73/sync-party-site
      - ./src/static/admin:/var/www/client/static/admin
      - ./src/static/rest_framework:/var/www/client/static/rest_framework
    depends_on:
      - web-app
  mongodb:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: $${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: $${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: $${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    env_file: ./.env.prod
