version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c 'gunicorn --workers 3 --bind $${DJANGO_HOST}:$${DJANGO_PORT} config.wsgi:application'
    env_file: .env.prod
    expose:
      - 8000
    depends_on:
      - mongodb
  nginx:
    image: nginx
    ports:
      - "1337:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/var/www/static:ro
    depends_on:
      - web-app
  mongodb:
    image: mongo:5.0
    restart: always
    volumes:
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongodb/data:/data:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: $${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: $${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: $${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    env_file: .env.prod
