version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: sh -c 'cd src && gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application'
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web-app