name: Docker Image CI

on:
  push:
    branches: [ fastapi, develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        context: .
        file: ./Dockerfile
        run: docker build . --tag web-app:$(date +%s)
